- hosts: localhost
  remote_user: root
  become: true
  vars:
    nodejs_npm_global_packages:
      - name: forever
  roles:
    - role: geerlingguy.nodejs
  tasks:
    - name: check App folder does't already exist
      file:
        path: App
        state: absent
    - name: Clone repo
      command: git clone https://github.com/CSC-DevOps/App
    - name: npm install
      npm:
        path: App/
    - name: run app
      command: /usr/local/lib/npm/bin/forever start App/main.js
    - name: check bash version
      apt:
        name: bash
        state: latest
    - name: check openssl version
      apt:
        name: openssl
        state: latest
    - name: check openssh-client version
      apt:
        name: openssh-client
        state: latest
    - name: check openssh-server version
      apt:
        name: openssh-server
        state: latest
    - name: clean-up of contents in /tmp/*
      shell: rm -rf /tmp/*   
      args:
        warn: False